Se agrega modulo para RID Cycling

diff --git a/rpcenum b/rpcenum
--- a/rpcenum
+++ b/rpcenum
@@ -31,6 +31,7 @@ function helpPanel(){
 	echo -e "\t\t${grayColour}DUsersInfo${endColour}${redColour} (Domain Users with info)${endColour}"
 	echo -e "\t\t${grayColour}DAUsers ${redColour}(Domain Admin Users)${endColour}"
 	echo -e "\t\t${grayColour}DGroups ${redColour}(Domain Groups)${endColour}"
+	echo -e "\t\t${grayColour}RIDs${endColour}${redColour} (RID Cycling)${endColour}"
 	echo -e "\t\t${grayColour}All ${redColour}(All Modes)${endColour}"
 	echo -e "\n\t${purpleColour}i)${endColour}${yellowColour} Host IP Address${endColour}"
 	echo -e "\n\t${purpleColour}h)${endColour}${yellowColour} Show this help pannel${endColour}"
@@ -210,6 +211,43 @@ function extract_DGroups(){
 	rm $tmp_file 2>/dev/null
 }
 
+function ridCycling(){
+    local host_ip=$1
+    local base_user="guest"
+    local sid_base=""
+
+    echo -e "\n${yellowColour}[*]${endColour}${grayColour} Starting RID cycling with user '$base_user' on host $host_ip...${endColour}\n"
+    
+    # Obtener el SID base utilizando 'administrator' como referencia
+
+	command_ridc="rpcclient $rpcclient_auth $host_ip -c \"lookupnames administrator\""
+	echo "rpcclient $rpcclient_auth $host_ip"
+    sid_info=$(eval $command_ridc 2>/dev/null) 
+    sid_base=$(echo "$sid_info" | grep -oP 'S-\d+(-\d+){3,}' | sed 's/-[^-]*$//')
+
+    if [[ -z "$sid_base" ]]; then
+        echo -e "${redColour}[!] Failed to retrieve SID base. Ensure 'guest' account has access.${endColour}"
+        return 1
+    fi
+
+    echo -e "${blueColour}[+]${endColour} SID base found: ${sid_base}\n"
+
+    # Ejecutar lookupsids para el rango de RIDs (400-2000) y capturar output
+    echo "Name" > $tmp_file
+
+	command_ridc2="seq 400 2000 | xargs -P 50 -I {} rpcclient $rpcclient_auth $host_ip -c \"lookupsids ${sid_base}-{}\""
+
+	eval "$command_ridc2" | grep -v unknown >> "$tmp_file"
+
+    #Mostrar los resultados en una tabla
+   	echo -ne "${blueColour}"
+    printTable ',' "$(cat $tmp_file)"
+    echo -ne "${endColour}"
+	cat $tmp_file > rid-cycling.txt
+    rm $tmp_file 2>/dev/null
+}
+
+
 function extract_All(){
 	extract_DUsers $1
 	extract_DUsers_Info $1
@@ -232,10 +270,10 @@ function beginEnumeration(){
   	echo "Using rpcclient authentication: $rpcclient_auth"
 	
 	#rpcclient $rpcclient_auth $host_ip -c "enumdomusers" > /dev/null 2>&1
-	command="rpcclient $rpcclient_auth $host_ip -c \"enumdomusers\""
-	$(eval $command > /dev/null 2>&1)
+	#command="rpcclient $rpcclient_auth $host_ip -c \"enumdomusers\""
+	#$(eval $command > /dev/null 2>&1)
 
-	if [ "$(echo $?)" == "0" ]; then
+	#if [ "$(echo $?)" == "0" ]; then
 		if [ "$port_status" == "0" ]; then
 			case $enum_mode in
 				DUsers)
@@ -250,6 +288,9 @@ function beginEnumeration(){
 				DGroups)
 					extract_DGroups $host_ip
 					;;
+				RIDs)
+					ridCycling $host_ip
+					;;
 				All)
 					extract_All $host_ip
 					;;
@@ -260,13 +301,13 @@ function beginEnumeration(){
 					;;
 			esac
 		else
-			echo -e "\n${redColour}Port 139 seems to be closed on $host_ip${endColour}"
+			echo -e "\n${redColour}Port 135 seems to be closed on $host_ip${endColour}"
 			tput cnorm; exit 0
 		fi
-	else
-		echo -e "\n${redColour}[!] Error: Access Denied${endColour}"
-		tput cnorm; exit 0
-	fi
+	#else
+	#	echo -e "\n${redColour}[!] Error: Access Denied${endColour}"
+	#	tput cnorm; exit 0
+	#fi
 }
 
 # Main Function
